[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.localnet]
csvp_protocol = "GXvE4L1kKLdQZpGruFQbg9i8jR2GFBbZqDT3uvXAEfGs"
registration = "CGZp3yAZwuL9WQbQYpWRgw3fTyXesExjtoSi7sfC29zu" 

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/voting.ts"

address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/media/alex/UbuntuExt/source/repos/ConfidentialSolanaVoteProtocol/artifacts/arcium_program_0.3.0.so"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/media/alex/UbuntuExt1/source/repos/ConfidentialSolanaVoteProtocol/artifacts/arcium_program_0.3.0.so"

[[test.validator.account]]
address = "FHriyvoZotYiFnbUzKFjzRSb2NiaC8RPWY7jtKuKhg65"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "7MGSS4iKNM4sVib7bDZDJhVqB6EcchPwVnTKenCY1jt3"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "7ZoV8Ps6NcLo5RERnGndmaBXDwxHvhUxzNBDDFyMZuKY"
filename = "artifacts/wallet_acc_7ZoV_ZuKY.json"

[[test.validator.account]]
address = "6X8U7w7Vn6ndFfhmEkGxkpFY5qsNfp6YgVKtbv5uBdGL"
filename = "artifacts/arx_ata_7ZoV_ZuKY.json"

[[test.validator.account]]
address = "9LKgHRSup1DFcZNNLFJTs95WEdV455bNC3Wg888mP389"
filename = "artifacts/wallet_acc_9LKg_P389.json"

[[test.validator.account]]
address = "BmwwV42SNBdzg7TGZtJcmzHuh3GB9Hr8hT4sEonEodFe"
filename = "artifacts/wallet_acc_callback_Bmww_odFe.json"

[[test.validator.account]]
address = "BtJutMg7W61GAqAdgtBMLJCTqJiRJQiJPrkbexYiwCkx"
filename = "artifacts/arx_ata_9LKg_P389.json"

[[test.validator.account]]
address = "E6ANEzikyr5sJLNzqhjJYdkBzWjTqFuKvtVQ9c3DuTw"
filename = "artifacts/operator_acc_9LKg_P389.json"

[[test.validator.account]]
address = "ELoRR19zrps1G3UYKcAxr7LKbw3kbqkVUXVY9dETMWN7"
filename = "artifacts/arx_node_9LKg_P389.json"

[[test.validator.account]]
address = "7tzFG8kAzdmrRkhc7bguGYgcRdaJc2XpPz5xhAoymk6j"
filename = "artifacts/wallet_acc_7tzF_mk6j.json"

[[test.validator.account]]
address = "3sGU54n6tS5ZMr2FyWshEcCQCvnkcyJMUbr6TGyt5iCQ"
filename = "artifacts/wallet_acc_callback_3sGU_5iCQ.json"

[[test.validator.account]]
address = "7oruGCySZzheJsJXjpw9n7LyDZD8FFr19WrTXNC3Wu4U"
filename = "artifacts/arx_ata_7tzF_mk6j.json"

[[test.validator.account]]
address = "BssWd25savxphVDEcjPTvT3uFXZxrEstrFtmRG6MZ1cz"
filename = "artifacts/operator_acc_7tzF_mk6j.json"

[[test.validator.account]]
address = "XdfSwb8ZajhN7CerfBSJVhyfx5fyLtv34QVKSRgMFA9"
filename = "artifacts/arx_node_7tzF_mk6j.json"

[[test.validator.account]]
address = "GgSqqAyH7AVY3Umcv8NvncrjFaNJuQLmxzxFxPoPW2Yd"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "Gn6Lhb2Vqic3iuuUkAZjjY7C3bEbNPn3v6VJKqEZ9CMS"
filename = "artifacts/init_vote_stats_raw_circuit_0.json"

[[test.validator.account]]
address = "4oEdovXuXF4yfgK71GkRgr54sZDyWuEJoQWXWG1cgYix"
filename = "artifacts/reveal_result_raw_circuit_0.json"

[[test.validator.account]]
address = "78azSeNoLuZuKyBsdAPoSupMxvsPeGWJNmMNuPZ4qUdJ"
filename = "artifacts/vote_raw_circuit_0.json"

[[test.validator.account]]
address = "A4tTFGqmGyeeBSfhJiAkdJFanZXb9Qsr113KD35ecxmC"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "8Pj1SxxBYKGCjj5Q3dCBNUE58CJKSPfEg5ViPqb8YqLM"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "EwTEfgSkxne3SGJdb1cuYc6ZTm9FdjhNGTBRUY1MasFL"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "87AsDiuSMb8CMyGohvYkQGGBbwpjkSnDkH8pwLCjEgkZ"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "By1z3Jc8V7WspWvDhTUmrcWM64BsCHkS7evkvXnjUgc9"
filename = "artifacts/executing_pool_acc.json"
