[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.localnet]
csvp_protocol = "GXvE4L1kKLdQZpGruFQbg9i8jR2GFBbZqDT3uvXAEfGs"
registration = "CGZp3yAZwuL9WQbQYpWRgw3fTyXesExjtoSi7sfC29zu" 

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/voting.ts"

